### ISSUE TITLE
Chart not refreshed when data changes

### ISSUE THREAD

**Issue by melalj** [99ff00/react-charty#6] opened 2020-03-01 16:19 UTC
I'm storing the data on the state like this:

```js
class CalendarActivity extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      data: null
    };
  }

  async componentDidMount() {
    const { year } = this.props;
    await this.setData(year);
  }

  async componentDidUpdate(prevProps) {
    const { year } = this.props;
    if (prevProps.year !== year) {
      await this.setData(year);
    }
  }

  async setData(year) {
    const dataActivity = await queryActivity(year);
    const days = enumerateDaysBetweenDates(`${year}-01-01`, `${year}-12-31`);
    const data = { x: [], y0: [] };
    days.forEach(d => {
      const row = dataActivity.find(v => v.day === d);
      data.x.push(convertDayToDate(d).getTime());
      data.y0.push(row ? row.count : 0);
    });
    this.setState({ data });
  }

  render() {
    const { data } = this.state;

    if (!data) return null;

    return (
      <Charty
        title="Messages"
        theme={LIGHT_THEME}
        style={{ width: '100%' }}
        yAxisType="number"
        xAxisType="date"
        rangeTextType="longDate"
        names={{ y0: 'Messages' }}
        colors={{ y0: mainColor }}
        type="bar"
        data={data}
      />
    );
  }
}
```

When I change the prop `year`, it requests for new data and updates the state.
Charty doesn't update the data accordingly and renders empty data or broken result:
<img width="1013" alt="Screenshot 2020-03-01 17 18 32" src="https://user-images.githubusercontent.com/3869766/75629267-c094ca80-5be0-11ea-9475-faeaeca45a2b.png">

It seems that the chart doesn't affect the data changes properly.

**Comment by 99ff00** [comment] 2020-03-08 13:57
@melalj Hi, sorry for the late response. Could you please post the value of `data` variable in `render` function for 2-3 cases, e.g. 2015, 2016, 2017 years?

**Comment by melalj** [comment] 2020-03-09 09:35
@99ff00 Thanks Aleksandr!
I just made a code sandbox of the example: https://codesandbox.io/s/inspiring-breeze-it8fx

**Comment by 99ff00** [comment] 2020-03-09 16:19
@melalj Please try this release: https://github.com/99ff00/react-charty/releases/tag/v0.1.6
I think the problem is fixed now. The sandbox is available here:
https://codesandbox.io/s/bitter-platform-sm297

**Closed** 2020-03-24 14:00 UTC
Labels: bug, fixed
